// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs-bpjcASSTQcughpHT_csFT6N3LTASkY',
    appId: '1:812210093339:web:6523f541ecc1493b4b27be',
    messagingSenderId: '812210093339',
    projectId: 'tienda3-3d9da',
    authDomain: 'tienda3-3d9da.firebaseapp.com',
    storageBucket: 'tienda3-3d9da.appspot.com',
    measurementId: 'G-ZF6THW3B1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9ms0MFVvXmgMpe3Tq_WVAuWdZKlKhb-g',
    appId: '1:812210093339:android:91a863e54b27e51b4b27be',
    messagingSenderId: '812210093339',
    projectId: 'tienda3-3d9da',
    storageBucket: 'tienda3-3d9da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEgWKX5NKy2UaHtu6UkJGB8-mYpS3ItJ4',
    appId: '1:812210093339:ios:442104362c0045fe4b27be',
    messagingSenderId: '812210093339',
    projectId: 'tienda3-3d9da',
    storageBucket: 'tienda3-3d9da.appspot.com',
    iosBundleId: 'com.example.tienda3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEgWKX5NKy2UaHtu6UkJGB8-mYpS3ItJ4',
    appId: '1:812210093339:ios:442104362c0045fe4b27be',
    messagingSenderId: '812210093339',
    projectId: 'tienda3-3d9da',
    storageBucket: 'tienda3-3d9da.appspot.com',
    iosBundleId: 'com.example.tienda3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs-bpjcASSTQcughpHT_csFT6N3LTASkY',
    appId: '1:812210093339:web:80305532ebdf841a4b27be',
    messagingSenderId: '812210093339',
    projectId: 'tienda3-3d9da',
    authDomain: 'tienda3-3d9da.firebaseapp.com',
    storageBucket: 'tienda3-3d9da.appspot.com',
    measurementId: 'G-T1GD6Y7PL5',
  );

}